db.serverUrl=jdbc:mysql://networksimulator.mysql.database.azure.com:3306/?useSSL=true&requireSSL=true
db.url=jdbc:mysql://networksimulator.mysql.database.azure.com:3306/network_db?useSSL=true&requireSSL=true
db.username=nadirkutluozen
db.password=1234811llA!